### ISSUE TITLE
Strange problem crashes after updating

### ISSUE THREAD

**Issue by shenyx110** [XxRexRaptorxX/RuneCraft#4]
[minecraft-exported-crash-info-2023-06-27T09-59-53.zip](https://github.com/XxRexRaptorxX/RuneCraft/files/11876950/minecraft-exported-crash-info-2023-06-27T09-59-53.zip)
[minecraft-exported-logs-2023-06-27T09-59-47.log](https://github.com/XxRexRaptorxX/RuneCraft/files/11876953/minecraft-exported-logs-2023-06-27T09-59-47.log)
This is a crash updated to the latest version. v.3.7.3
[minecraft-exported-logs-2023-06-27T10-08-41.log](https://github.com/XxRexRaptorxX/RuneCraft/files/11876956/minecraft-exported-logs-2023-06-27T10-08-41.log)
There is no problem with the old version. v.3.7.2

**Comment by XxRexRaptorxX** [comment]
In v.3.7.3 is the Patchouli mod mandatory again. Install the mod and everthing should work
